// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9WIpv8F6QLxDH2_6iUA4iQmFiT7UbLxo',
    appId: '1:692780092822:web:7ec4ecca73d202b84361b7',
    messagingSenderId: '692780092822',
    projectId: 'levelup-44c32',
    authDomain: 'levelup-44c32.firebaseapp.com',
    storageBucket: 'levelup-44c32.firebasestorage.app',
    measurementId: 'G-76YM6JFW9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSY8kGgnQHrlN19r-pW3RoqfEIZeQhOU',
    appId: '1:692780092822:android:f929fb22ac7e3b4d4361b7',
    messagingSenderId: '692780092822',
    projectId: 'levelup-44c32',
    storageBucket: 'levelup-44c32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhaHIgJkhDpINNXjVGCLiNrWAEY0NRKc',
    appId: '1:692780092822:ios:2b9ddc82903a25f74361b7',
    messagingSenderId: '692780092822',
    projectId: 'levelup-44c32',
    storageBucket: 'levelup-44c32.firebasestorage.app',
    iosBundleId: 'com.example.myDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhaHIgJkhDpINNXjVGCLiNrWAEY0NRKc',
    appId: '1:692780092822:ios:2b9ddc82903a25f74361b7',
    messagingSenderId: '692780092822',
    projectId: 'levelup-44c32',
    storageBucket: 'levelup-44c32.firebasestorage.app',
    iosBundleId: 'com.example.myDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9WIpv8F6QLxDH2_6iUA4iQmFiT7UbLxo',
    appId: '1:692780092822:web:a4d7489ebbecbf964361b7',
    messagingSenderId: '692780092822',
    projectId: 'levelup-44c32',
    authDomain: 'levelup-44c32.firebaseapp.com',
    storageBucket: 'levelup-44c32.firebasestorage.app',
    measurementId: 'G-J7YP2XC7S8',
  );
}
